# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  delay=1000
  cmd = "make swag go build -o ./tmp/main ./cmd/api"
  bin = "tmp/main"
  pre_build = "swag init"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "tests", "docs"]


[log]
  time = true
