definitions:
  requests.AuthorizationRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
  requests.ProductRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  requests.RoleRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  requests.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  requests.UserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  requests.UserSendOTPRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  requests.UserVerifOTPRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
  responses.RoleResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Logs in a user
      parameters:
      - description: Login User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: login success
          schema:
            additionalProperties: true
            type: object
      summary: User login
      tags:
      - auth
  /api/v1/auth/regis:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Register User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: registration user success
          schema:
            additionalProperties: true
            type: object
      summary: User registration
      tags:
      - auth
  /api/v1/auth/send-otp:
    post:
      consumes:
      - application/json
      description: Send an OTP to user's email
      parameters:
      - description: Send OTP
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/requests.UserSendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: otp code has been send
          schema:
            additionalProperties: true
            type: object
      summary: Send OTP
      tags:
      - auth
  /api/v1/auth/verif-otp:
    post:
      consumes:
      - application/json
      description: Verify OTP for a user
      parameters:
      - description: Verify OTP
        in: body
        name: otp
        required: true
        schema:
          $ref: '#/definitions/requests.UserVerifOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: otp verification success
          schema:
            additionalProperties: true
            type: object
      summary: Verify OTP
      tags:
      - auth
  /api/v1/authorizations:
    get:
      consumes:
      - application/json
      description: Get all authorization
      parameters:
      - default: "10"
        description: Limit
        in: query
        name: limit
        type: string
      - default: "1"
        description: Page
        in: query
        name: page
        type: string
      - description: Sort By
        in: query
        name: sort_by
        type: string
      - description: Filters
        in: query
        name: filters
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get all authorization success
          schema:
            additionalProperties: true
            type: object
      summary: Get all authorization
      tags:
      - authorization
    post:
      consumes:
      - application/json
      description: Create new authorization
      parameters:
      - description: Create new authorization
        in: body
        name: authorization
        required: true
        schema:
          $ref: '#/definitions/requests.AuthorizationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: create new authorization success
          schema:
            additionalProperties: true
            type: object
      summary: Create new authorization
      tags:
      - authorization
  /api/v1/authorizations/{id}:
    delete:
      consumes:
      - application/json
      description: delete authorization by id
      parameters:
      - description: authorization id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Delete authorization by id success
          schema:
            additionalProperties: true
            type: object
      summary: delete authorization by id
      tags:
      - authorization
    get:
      consumes:
      - application/json
      description: Get authorization by id
      parameters:
      - description: authorization id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: get authorization by id success
          schema:
            additionalProperties: true
            type: object
      summary: Get authorization by id
      tags:
      - authorization
    put:
      consumes:
      - application/json
      description: Update authorization by id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update new authorization
        in: body
        name: authorization
        required: true
        schema:
          $ref: '#/definitions/requests.AuthorizationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: update authorization success
          schema:
            additionalProperties: true
            type: object
      summary: Update authorization by id
      tags:
      - authorization
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get all product
      parameters:
      - default: "10"
        description: Limit
        in: query
        name: limit
        type: string
      - default: "1"
        description: Page
        in: query
        name: page
        type: string
      - description: Sort By
        in: query
        name: sort_by
        type: string
      - description: Filters
        in: query
        name: filters
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get all product success
          schema:
            additionalProperties: true
            type: object
      summary: Get all product
      tags:
      - product
    post:
      consumes:
      - application/json
      description: Create new product
      parameters:
      - description: Create new product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/requests.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: create new product success
          schema:
            additionalProperties: true
            type: object
      summary: Create new product
      tags:
      - product
  /api/v1/products/{id}:
    delete:
      consumes:
      - application/json
      description: delete product by id
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Delete product by id success
          schema:
            additionalProperties: true
            type: object
      summary: delete product by id
      tags:
      - product
    get:
      consumes:
      - application/json
      description: Get product by id
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: get product by id success
          schema:
            additionalProperties: true
            type: object
      summary: Get product by id
      tags:
      - product
    put:
      consumes:
      - application/json
      description: Update product by id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update new product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/requests.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: update product success
          schema:
            additionalProperties: true
            type: object
      summary: Update product by id
      tags:
      - product
  /api/v1/roles:
    get:
      consumes:
      - application/json
      description: Get all role
      parameters:
      - default: "10"
        description: Limit
        in: query
        name: limit
        type: string
      - default: "1"
        description: Page
        in: query
        name: page
        type: string
      - description: Sort By
        in: query
        name: sort_by
        type: string
      - description: Filters
        in: query
        name: filters
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get all role success
          schema:
            additionalProperties: true
            type: object
      summary: Get all role
      tags:
      - role
    post:
      consumes:
      - application/json
      description: Create new role
      parameters:
      - description: Create new role
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/requests.RoleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.RoleResponse'
      summary: Create new role
      tags:
      - role
  /api/v1/roles/{id}:
    delete:
      consumes:
      - application/json
      description: Delete role by id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: delete role success
          schema:
            type: string
      summary: Delete role by id
      tags:
      - role
    get:
      consumes:
      - application/json
      description: Get role by id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.RoleResponse'
      summary: Get role by id
      tags:
      - role
    put:
      consumes:
      - application/json
      description: Update role by id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update role
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/requests.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.RoleResponse'
      summary: Update role by id
      tags:
      - role
  /api/v1/roles/{roles_id}/authorizations:
    get:
      consumes:
      - application/json
      description: Get authorizations by role id
      parameters:
      - description: Role ID
        in: path
        name: roles_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: get authorizations by role id success
          schema:
            additionalProperties: true
            type: object
      summary: Get authorizations by role id
      tags:
      - role-authorization
  /api/v1/roles/{roles_id}/authorizations/{authorizations_id}:
    delete:
      consumes:
      - application/json
      description: Remove authorization from role
      parameters:
      - description: Role ID
        in: path
        name: roles_id
        required: true
        type: integer
      - description: Authorization ID
        in: path
        name: authorizations_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: remove authorization from role success
          schema:
            additionalProperties: true
            type: object
      summary: Remove authorization from role
      tags:
      - role-authorization
    post:
      consumes:
      - application/json
      description: Assign authorization to role
      parameters:
      - description: Role ID
        in: path
        name: roles_id
        required: true
        type: integer
      - description: Authorization ID
        in: path
        name: authorizations_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: assign authorization to role success
          schema:
            additionalProperties: true
            type: object
      summary: Assign authorization to role
      tags:
      - role-authorization
  /api/v1/users/me:
    get:
      consumes:
      - application/json
      description: Get data of authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: user data fetched successfully
          schema:
            additionalProperties: true
            type: object
      summary: Get User Data
      tags:
      - users
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
